apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-framework-petclinic
  namespace: openshift-gitops
spec:
  destination:
    namespace: sample
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: application-manifest
    repoURL: https://github.com/ksingh7/argocd-openshift
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    # syncOptions:
    # - CreateNamespace=true